#!/bin/bash
# release
#
#{{IS_NOTE
#	Purpose:
#		
#	Description:
#		
#	History:
#		Tue Mar 3 11:11:09     2011, Created by Jimmy
#}}IS_NOTE
#
#Copyright (C) 2011 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#}}IS_RIGHT
#
maindir="$(pwd)"
maindir="${maindir%/cmldoc}"
cd $maindir
echo "Working directory $maindir"
stamp=$(date +%Y%m%d)
oldVersion=$1
newVersion=$2
isFL=$3

if [ "$oldVersion" == "" ] || [ "$newVersion" == "" ] ; then
	echo "Usage: upVer [ oldVersion ] [ newVersion ] [ FL ]"
	exit 1
fi

function upVer {
	sed -i "s/$oldVersion/$newVersion/g" $maindir/version
	if [ "$isFL" == "FL" ] ; then
		sed -i "1,/description/s/version>.*<\/version/version>$newVersion-SNAPSHOT<\/version/" $maindir/pom.xml
	else
		sed -i "1,/description/s/version>.*<\/version/version>$newVersion<\/version/" $maindir/pom.xml
	fi
	find $maindir/$1/src -name config.xml -exec sed -i "s/version-uid>.*<\/version-uid/version-uid>$newVersion<\/version-uid/" {} \;
	find $maindir/$1/src -name lang-addon.xml -exec sed -i "s/version-uid>.*<\/version-uid/version-uid>$newVersion<\/version-uid/" {} \;
	find $maindir/$1/src -name Version.java -exec sed -i "s/UID.*;/UID = \"$newVersion\";/g" {} \;
	echo "Update $1 version to $newVersion"
}

upVer